name: flutter_map_text_marker
description: A flutter_map MapPlugin that gives a user the ability to add custom text markers to the map.
version: 0.0.3
repository: https://github.com/XAER/flutter_map_text_marker

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^1.0.0
  latlong2: ^0.8.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
